all:
	g++ -std=c++11 -Wall -Wextra -Wpedantic main.cpp -O2 -march=native -mtune=native -I../include/ -I../extlib/ -I../extlib/greens_functions/build ../extlib/greens_functions/build/libgreens_functions.a -lgsl
